/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SQUAREL_H_RPCGEN
#define _SQUAREL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct squarel_in {
	long in;
};
typedef struct squarel_in squarel_in;

struct squarel_out {
	long out;
};
typedef struct squarel_out squarel_out;

#define SQUAREL_PROG 0x31230000
#define SQUAREL_VERS1 1

#if defined(__STDC__) || defined(__cplusplus)
#define SQUARELPROG 1
extern  squarel_out * squarelprog_1(squarel_in *, CLIENT *);
extern  squarel_out * squarelprog_1_svc(squarel_in *, struct svc_req *);
extern int squarel_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SQUARELPROG 1
extern  squarel_out * squarelprog_1();
extern  squarel_out * squarelprog_1_svc();
extern int squarel_prog_1_freeresult ();
#endif /* K&R C */
#define SQUAREL_VERS2 2

#if defined(__STDC__) || defined(__cplusplus)
extern  squarel_out * squarelprog_2(squarel_in *, CLIENT *);
extern  squarel_out * squarelprog_2_svc(squarel_in *, struct svc_req *);
extern int squarel_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern  squarel_out * squarelprog_2();
extern  squarel_out * squarelprog_2_svc();
extern int squarel_prog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_squarel_in (XDR *, squarel_in*);
extern  bool_t xdr_squarel_out (XDR *, squarel_out*);

#else /* K&R C */
extern bool_t xdr_squarel_in ();
extern bool_t xdr_squarel_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SQUAREL_H_RPCGEN */
