/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "squarel.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

squarel_out *
squarelprog_1(squarel_in *argp, CLIENT *clnt)
{
	static squarel_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SQUARELPROG,
		(xdrproc_t) xdr_squarel_in, (caddr_t) argp,
		(xdrproc_t) xdr_squarel_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

squarel_out *
squarelprog_2(squarel_in *argp, CLIENT *clnt)
{
	static squarel_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SQUARELPROG,
		(xdrproc_t) xdr_squarel_in, (caddr_t) argp,
		(xdrproc_t) xdr_squarel_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
