/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "squarel.h"

bool_t
xdr_squarel_in (XDR *xdrs, squarel_in *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->in))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_squarel_out (XDR *xdrs, squarel_out *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->out))
		 return FALSE;
	return TRUE;
}
