/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "squarel.h"


void
squarel_prog_1(char *host)
{
	CLIENT *clnt;
	squarel_out  *result_1;
	squarel_in  squarelprog_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SQUAREL_PROG, SQUAREL_VERS1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = squarelprog_1(&squarelprog_1_arg, clnt);
	if (result_1 == (squarel_out *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("The back result = %d\n", result_1->out);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
squarel_prog_2(char *host)
{
	CLIENT *clnt;
	squarel_out  *result_1;
	squarel_in  squarelprog_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SQUAREL_PROG, SQUAREL_VERS2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = squarelprog_2(&squarelprog_2_arg, clnt);
	if (result_1 == (squarel_out *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	squarel_prog_1 (host);
	squarel_prog_2 (host);
exit (0);
}
