/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "wolf_rpc.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
wolf_rpc_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		wolf_rpc_data_t wolf_rpcc_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case WOLF_RPCC:	
		_xdr_argument = (xdrproc_t) xdr_wolf_rpc_data_t;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) wolf_rpcc_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
wolf_rpc_prog_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		wolf_rpc_data_t wolf_rpcc_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case WOLF_RPCC:
		_xdr_argument = (xdrproc_t) xdr_wolf_rpc_data_t;
		_xdr_result = (xdrproc_t) xdr_wolf_rpc_data_t;
		local = (char *(*)(char *, struct svc_req *)) wolf_rpcc_2_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}


int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	//(2)To do: use wolf_pmap_unset, to use port bigger than 1024
	wolf_pmap_unset(WOLF_RPC_PROG, WOLF_RPC_VERS1);
	wolf_pmap_unset(WOLF_RPC_PROG, WOLF_RPC_VERS2);
	
	//pmap_unset (WOLF_RPC_PROG, WOLF_RPC_VERS1);
	//pmap_unset (WOLF_RPC_PROG, WOLF_RPC_VERS2);

	int sock = create_udp_sock();
	transp = svcudp_create(sock);
	//transp = svcudp_create(RPC_ANYSOCK);
	
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, WOLF_RPC_PROG, WOLF_RPC_VERS1, wolf_rpc_prog_1, 0/*IPPROTO_UDP*/)) {
		fprintf (stderr, "%s", "unable to register (WOLF_RPC_PROG, WOLF_RPC_VERS1, udp).");
		exit(1);
	}
	if (!svc_register(transp, WOLF_RPC_PROG, WOLF_RPC_VERS2, wolf_rpc_prog_2, 0/*IPPROTO_UDP*/)) {
		fprintf (stderr, "%s", "unable to register (WOLF_RPC_PROG, WOLF_RPC_VERS2, udp).");
		exit(1);
	}
	
	wolf_pmap_set(WOLF_RPC_PROG, WOLF_RPC_VERS1, IPPROTO_UDP, transp->xp_port);
	wolf_pmap_set(WOLF_RPC_PROG, WOLF_RPC_VERS2, IPPROTO_UDP, transp->xp_port);
	
	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
