/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */


#include "wolf_rpc.h"

/* begin -- below functions are new added by wolf */

int set_tcp_keep_alive(int s, int keepidle, int keepintvl, int keepcnt)
{
	int optval = 1;
	socklen_t optlen = sizeof(optval);

	if(setsockopt(s, SOL_SOCKET, SO_KEEPALIVE, &optval, optlen) < 0) 
	{
		fprintf(stderr, "%s():%d: %m\n", __FUNCTION__, __LINE__);
		return -2;
	}

	if(setsockopt(s, SOL_TCP, TCP_KEEPIDLE, &keepidle, optlen) < 0) 
	{
		fprintf(stderr, "%s():%d: %m\n", __FUNCTION__, __LINE__);
		return -16;
	}

	if(setsockopt(s, SOL_TCP, TCP_KEEPCNT, &keepcnt, optlen) < 0)
	{
		fprintf(stderr, "%s():%d: %m\n", __FUNCTION__, __LINE__);
		return -1024;
	}

	return 0;
}

wolf_rpc_clnt_t *wolf_clnt_create_f0(int max_clnts, const char *hostname, unsigned int prog,
	unsigned int vers, int proto, const char *caller,
	struct timeval *timeout, struct timeval *retry_timeout, u_int32_t flags)
{
	wolf_rpc_clnt_t *rpc_clnt = (wolf_rpc_clnt_t *)malloc(sizeof(wolf_rpc_clnt_t));
	if(rpc_clnt == NULL)
	{
		printf("%s(): malloc for rpc_clnt failed\n", __FUNCTION__);
		return NULL;
	}
	memset(rpc_clnt, 0, sizeof(wolf_rpc_clnt_t));
	
	CLIENT *clnt;

	//(1)To do: use list to control the clnt
	
	//clnt = clnt_create (hostname, prog, vers, proto);
	clnt = new_clnt_create(hostname, hostname, prog, vers, proto);
	if(clnt == NULL)
	{
		clnt_pcreateerror (hostname);
		exit (1);
	}

	//(3)To do: timeout issue
	if(flags & WOLF_RPC_CLNT_FLAGS_tcp_keepalive)
	{
		//set_tcp_keep_alive(((struct ct_data *)clnt->cl_private)->ct_sock, 4, 4, 120);
	}

	if(timeout && (timeout->tv_sec > 0 || timeout->tv_usec > 0))
	{
		clnt_control(clnt, CLSET_TIMEOUT, (char *)timeout);
	}

	if(retry_timeout && (retry_timeout->tv_sec > 0 || retry_timeout->tv_usec > 0))
	{
		clnt_control(clnt, CLSET_RETRY_TIMEOUT, (char *)retry_timeout);
	}

	rpc_clnt->clnt = clnt;
	
	return rpc_clnt;
}
	
/* end -- below functions are new added by wolf */

void
wolf_rpc_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	wolf_rpc_data_t  wolf_rpcc_1_arg;
	bzero(&wolf_rpcc_1_arg, sizeof(wolf_rpc_data_t));
	
	wolf_rpcc_1_arg.type = 1;
	wolf_rpcc_1_arg.len = 1;

#ifndef WOLF_CLINET
#ifndef	DEBUG
	clnt = clnt_create (host, WOLF_RPC_PROG, WOLF_RPC_VERS1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif
#else //my new code
	wolf_rpc_clnt_t *p_hdl;
	//(4)To do: using TCP instead of UDP
	p_hdl = wolf_clnt_create_f0(NUM_RPC_CLNTS, host, WOLF_RPC_PROG, WOLF_RPC_VERS1, IPPROTO_UDP,
					NULL, NULL, NULL, 0);
	if(p_hdl == NULL || p_hdl->clnt == NULL)
	{
		printf("%s(): p_hdl or p_hdl->clnt is NULL\n", __FUNCTION__);
		exit(1);
	}
	clnt = p_hdl->clnt;
	
#endif	/* WOLF_CLINET */

	result_1 = wolf_rpcc_1(&wolf_rpcc_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
wolf_rpc_prog_2(char *host)
{
	CLIENT *clnt;
	wolf_rpc_data_t  *result_1;
	wolf_rpc_data_t  wolf_rpcc_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, WOLF_RPC_PROG, WOLF_RPC_VERS2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = wolf_rpcc_2(&wolf_rpcc_2_arg, clnt);
	if (result_1 == (wolf_rpc_data_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	printf("host: %s\n", host);
	wolf_rpc_prog_1 (host);
	//wolf_rpc_prog_2 (host);
exit (0);
}
