/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "wolf_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
wolf_rpcc_1(wolf_rpc_data_t *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, WOLF_RPCC,
		(xdrproc_t) xdr_wolf_rpc_data_t, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

wolf_rpc_data_t *
wolf_rpcc_2(wolf_rpc_data_t *argp, CLIENT *clnt)
{
	static wolf_rpc_data_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, WOLF_RPCC,
		(xdrproc_t) xdr_wolf_rpc_data_t, (caddr_t) argp,
		(xdrproc_t) xdr_wolf_rpc_data_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
