/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC1_H_RPCGEN
#define _RPC1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct _rpc1_data_t {
	int type;
	char data[0];
};
typedef struct _rpc1_data_t _rpc1_data_t;

typedef _rpc1_data_t rpc1_data_t;

#define RPC1_RPC_PROG 0x38000023
#define RPC1_RPC_VERS1 1

#if defined(__STDC__) || defined(__cplusplus)
#define RPC1_RPCC 1
extern  int * rpc1_rpcc_1(rpc1_data_t *, CLIENT *);
extern  int * rpc1_rpcc_1_svc(rpc1_data_t *, struct svc_req *);
extern int rpc1_rpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RPC1_RPCC 1
extern  int * rpc1_rpcc_1();
extern  int * rpc1_rpcc_1_svc();
extern int rpc1_rpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr__rpc1_data_t (XDR *, _rpc1_data_t*);
extern  bool_t xdr_rpc1_data_t (XDR *, rpc1_data_t*);

#else /* K&R C */
extern bool_t xdr__rpc1_data_t ();
extern bool_t xdr_rpc1_data_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

char *getSysTime_r(char *timestamp);

#endif /* !_RPC1_H_RPCGEN */
