/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc2.h"

#define DEBUG_RPC 1

void
rpc2_rpc_prog_1(char *host, char *pbuf)
{
	#ifdef DEBUG_RPC
		printf("host: %s, result: %s\n", host, pbuf);
	#endif

	CLIENT *clnt;
	int  *result_1;
	rpc2_data_t  rpc2_rpcc_1_arg;
	
	//copy the result
	memcpy(rpc2_rpcc_1_arg.data, pbuf, sizeof(rpc2_data_t));

#ifndef	DEBUG
	clnt = clnt_create (host, RPC2_RPC_PROG, RPC2_RPC_VERS1, "udp");
	if (clnt == NULL) {
		printf("%s(): clnet_create failed...\n", __FUNCTION__);
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = rpc2_rpcc_1(&rpc2_rpcc_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		printf("%s(): rpc2_rpcc_1 failed...\n", __FUNCTION__);
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


