/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc2.h"

bool_t
xdr__rpc2_data_t (XDR *xdrs, _rpc2_data_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->data, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc2_data_t (XDR *xdrs, rpc2_data_t *objp)
{
	register int32_t *buf;

	 if (!xdr__rpc2_data_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
