/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc1.h"

bool_t
xdr__rpc1_data_t (XDR *xdrs, _rpc1_data_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 0,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc1_data_t (XDR *xdrs, rpc1_data_t *objp)
{
	register int32_t *buf;

	 if (!xdr__rpc1_data_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
