/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc1.h"

#define DEBUG_RPC 1

void *
rpc1_rpc_prog_1(void *data)
{
	pthread_param_t *pthread_param = (pthread_param_t *)data;

	#ifdef DEBUG_RPC	
		printf("calling %s...host: %s, type: %d\n", __FUNCTION__, pthread_param->host, pthread_param->type);
	#endif

	CLIENT *clnt;
	int  *result_1;
	rpc1_data_t  rpc1_rpcc_1_arg;

	rpc1_rpcc_1_arg.type = pthread_param->type; //type number

#ifndef	DEBUG
	clnt = clnt_create (pthread_param->host, RPC1_RPC_PROG, RPC1_RPC_VERS1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (pthread_param->host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = rpc1_rpcc_1(&rpc1_rpcc_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

