/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc2.h"

int *
rpc2_rpcc_1_svc(rpc2_data_t *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	//print the time or pid number here
	printf("return back from rpc: %s\n", argp->data);

	return &result;
}
